theme: minima
title: Saverio Napolitano
description: Artificial Intelligence Engineering student at University of Modena and Reggio Emilia (Unimore), Italy. Exchange student at Mid Sweden University (MIUN).
